Shared volume support
Additionally, includes some cleanup

diff --git a/kind-cluster/install_csi_3x b/kind-cluster/install_csi_3x
--- a/kind-cluster/install_csi_3x
+++ b/kind-cluster/install_csi_3x
@@ -78,8 +78,8 @@ elif [[ $1 = "install" ]]; then
   sed -i 's/version: \"2\"/version: \"3\"/' ./example/client.yaml # set client version to an actual one
   sed -i 's/image: quay.io\/quobyte\/quobyte-client:2/image: quay.io\/quobyte\/quobyte-client:3/' ./example/client.yaml # set client version to an actual one
   #sed -i 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/' ./example/client.yaml # change imagePullPollsicy if needed
-  sed -i 's/value: <YOUR_QUOBYTE_REGISTRY>/value: testing.corp.quobyte.com/' ./example/client.yaml  # set quobyte registry address
-  sed -i 's/value: <QUOBYTE_MOUNT_POINT>/value: $QUOBYTE_MOUNT_POINT/' ./example/client.yaml
+  sed -i "s/value: <YOUR_QUOBYTE_REGISTRY>/value: $QUOBYTE_REGISTRY/" ./example/client.yaml  # set quobyte registry address
+  sed -i "s/value: <QUOBYTE_MOUNT_POINT>/value: $QUOBYTE_MOUNT_POINT/" ./example/client.yaml
   enable_access_keys=False
   if [[ "$MOUNT_WITH_ACCESS_KEYS" = 'y' ]]; then
     enable_access_keys=True
@@ -108,8 +108,11 @@ elif [[ $1 = "install" ]]; then
   #kubectl create -f  quobyte-csi-driver/k8s-snapshot-controller.yaml 
 
   # install csi helm package and verify if it's successfully installed
-  helm install $CSI_DRIVER ./quobyte-csi-driver --set quobyte.apiURL=$QUOBYTE_API_URL \
-    --set quobyte.enableSnapshots=False --set quobyte.enableAccessKeyMounts=$enable_access_keys
+  helm install $CSI_DRIVER ./quobyte-csi-driver --set quobyte.apiURL=${QUOBYTE_API_URL} \
+    --set quobyte.enableSnapshots=False --set quobyte.enableAccessKeyMounts=${enable_access_keys} \
+    --set quobyte.dev.csiProvisionerVersion=${CSI_DRIVER_VERSION} \
+    --set quobyte.dev.csiImage=${CSI_DRIVER_IMAGE} \
+    --set quobyte.sharedVolumesList="sharedVolume"
   
   helm list | grep "$CSI_DRIVER"
 
@@ -141,7 +144,8 @@ elif [[ $1 = "e2e" ]]; then
     STORAGE_CLASS="$CODE_BASE_DIR/example/access_keys/storage-class-api-and-mount-secret.yaml" ../e2e || die 'Failing e2e tests with api and mount secrets'
     STORAGE_CLASS="$CODE_BASE_DIR/example/access_keys/storage-class-generic-secret.yaml" ../e2e || die 'Failing e2e tests with generic secrets'
   else
-    ../e2e
+    STORAGE_CLASS="$CODE_BASE_DIR/example/StorageClass.yaml" ../e2e || die 'Failing e2e tests with exclusive volumes'
+    STORAGE_CLASS="$CODE_BASE_DIR/example/Storage-class-shared-volume.yaml" ../e2e || die 'Failing e2e tests with shared volumes'
   fi
   exit 0
 elif [[ $1 = "uninstall" ]]; then
diff --git a/kind-cluster/setup_k8s_cluster b/kind-cluster/setup_k8s_cluster
--- a/kind-cluster/setup_k8s_cluster
+++ b/kind-cluster/setup_k8s_cluster
@@ -7,7 +7,20 @@
 MOUNT_WITH_ACCESS_KEYS=${MOUNT_WITH_ACCESS_KEYS:-n}
 PATH="$(pwd):$PATH"
 CODE_BASE_DIR="$(pwd)"
-TEST_CLUSTER_DIR='kind-cluster/kind-csi-experiment-testing-corp' 
+TEST_CLUSTER_DIR='kind-cluster/kind-csi-experiment-testing-corp'
+
+if [ ! -z "$(git status --porcelain)" ]; then
+  echo 'Requires clean directory (no stage/unstaged/untracked files) in repo'
+  exit 1
+fi
+
+KIND_CLUSTER_NAME="quobyte-csi-experiment-testing"
+# do not tag version as latest - that would trigger pull always from registry
+CSI_DRIVER_VERSION="$(git rev-parse --short HEAD)"
+# dummy.quobyte.com is not a docker registry. We buid docker image locally
+# and make it available to kind nodes via 'kind load docker-image'
+CSI_DRIVER_IMAGE="dummy.quobyte.com/quobyte-csi-driver:${CSI_DRIVER_VERSION}"
+KUBECONFIG='/tmp/'
 
 rm -rf "${TEST_CLUSTER_DIR}"
 
@@ -18,7 +31,7 @@ cd "${TEST_CLUSTER_DIR}"
 echo "Creating a Dockerfile * * * * * * * * *  * * * * * * * * * * * * * * * * *"
 echo ""
 echo ""
-tee -a Dockerfile << END
+tee -a Dockerfile <<END
 FROM kindest/node:v1.25.0
 RUN apt-get -y update 
 RUN apt-get -y install wget && apt-get install -y git && apt install -y nano
@@ -28,6 +41,8 @@ ENV QUOBYTE_API_URL="http://testing-api.corp.quobyte.com:7860"
 ENV QUOBYTE_REGISTRY="testing.corp.quobyte.com"
 ENV CSI_PROVISIONER="csi.quobyte.com"
 ENV QUOBYTE_MOUNT_POINT=/mnt/quobyte/mounts
+ENV CSI_DRIVER_VERSION=$CSI_DRIVER_VERSION
+ENV CSI_DRIVER_IMAGE=$CSI_DRIVER_IMAGE
 ENV MOUNT_WITH_ACCESS_KEYS=$MOUNT_WITH_ACCESS_KEYS
 END
 
@@ -40,7 +55,7 @@ docker image ls | grep 'quobyte/kind-node-testing:v0'
 echo "Use the newly created image in the `kind` configuration: * * * * * * * * *"
 tee -a kind-config-testing.yaml << END
 kind: Cluster
-name: quobyte-csi-experiment-testing
+name: ${KIND_CLUSTER_NAME}
 apiVersion: kind.x-k8s.io/v1alpha4
 nodes:
 - role: control-plane
@@ -64,6 +79,15 @@ echo  "Labeling Kubernetes nodes * * * * * * * * * * * * * * * * * * * * * * * *
 for node in $(kubectl get nodes --no-headers | awk '{print $1}'); do
   kubectl label nodes $node quobyte_client="true"
 done
+
+echo "Building local csi driver image"
+CODE_BASE_ROOT=${CODE_BASE_DIR} ${CODE_BASE_DIR}/src/build.sh
+docker build -t ${CSI_DRIVER_IMAGE} -f ${CODE_BASE_DIR}/src/Dockerfile ${CODE_BASE_DIR}/src
+if [[ "$?" -ne 0 ]]; then
+  echo "Failed to create local image (compile or image build failed!)"
+  exit 1
+fi
+kind load docker-image ${CSI_DRIVER_IMAGE} --name ${KIND_CLUSTER_NAME}
 
 echo "creating and setting default namespace to quobyte * * * * * * * * * * * *" 
 #to retrieve instances from all namespaces use '-A' argument
